# ==============================================================================
# DOCKER COMPOSE FILE - COMPILER ENVIRONMENT
# ==============================================================================
# 
# Usage:
#
#   - Build : docker-compose -f compose.yml build
#  

version: '2'

services:
  step1:
    build: step1/.
    container_name: step1
    image: step1
  step2:
    build: step2/.
    container_name: step2
    image: step2
    depends_on:
      - step1
  compilerenvironment:
    build: compiler-environment/.
    image: compiler-environment
    container_name: compiler-environment
    hostname: compiler-environment
    depends_on:
      - step2
    volumes:
      - ../develop:/develop


